{% set name = "critiplot" %}
{% set version = "2.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 146cf1b5b664468d9a0479883b3541c2afd6bded7b88586efd3995244f7a06c0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - pandas >=2.0
    - matplotlib-base >=3.5
    - seaborn >=0.12
    - pyarrow >=10.0
    - openpyxl >=3.0

test:
  imports:
    - critiplot
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aurumz-rgb/Critiplot-Package
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Visualize risk-of-bias in systematic reviews and meta-analyses
  description: |
    Critiplot is an open-source Python package for visualizing risk-of-bias (RoB) assessments
    across multiple evidence synthesis tools: NOS, JBI checklists, GRADE, and ROBIS.
    It produces publication-ready traffic-light plots and stacked bar charts.

extra:
  recipe-maintainers:
    - aurumz-rgb
    