{% set name = "critiplot" %}
{% set version = "2.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39164a2dbb95c419f2c72efcf8989df656336c6017623c378f557fc522d30d47

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - "python {{ python_min }}"
    - pip
    - setuptools
  run:
    - "python >={{ python_min }}"
    - "numpy >=2.2.2"
    - "pandas >=2.3.2"
    - "matplotlib-base >=3.9.2"
    - "seaborn >=0.13"
    - "pyarrow >=11"
    - "openpyxl >=3.1"
    - "streamlit >=1.40.0"

test:
  imports:
    - critiplot
  # skip pip check to avoid strict version conflicts
  commands: []

about:
  home: https://github.com/aurumz-rgb/Critiplot-Package
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Visualize risk-of-bias in systematic reviews and meta-analyses'
  description: |
    Critiplot is an open-source Python package for visualizing risk-of-bias (RoB) assessments
    across multiple evidence synthesis tools: Newcastle-Ottawa Scale (NOS), JBI Critical Appraisal
    Checklists, GRADE certainty of evidence, and ROBIS for systematic reviews. It produces
    publication-ready traffic-light plots and stacked bar charts for summarizing study quality.

extra:
  recipe-maintainers:
    - aurumz-rgb

